# Generated by Django 4.1.5 on 2023-01-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='select',
            field=models.CharField(choices=[('P', 'Статья'), ('N', 'Новость')], default='P', max_length=10, verbose_name='Статья/Новость'),
        ),
    ]
