# Generated by Django 4.1.5 on 2023-03-31 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0012_categoryuser_category_subscribers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='author',
            name='rating_author',
            field=models.IntegerField(default=0, verbose_name='Рейтинг автора'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(help_text='Имя категории', max_length=50, unique=True, verbose_name='Уникальная тема'),
        ),
        migrations.AlterField(
            model_name='categoryuser',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='categoryuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category', verbose_name='Категория:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating_post',
            field=models.IntegerField(default=0, verbose_name='Рейтинг:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='select',
            field=models.CharField(choices=[('P', 'Статья'), ('N', 'Новость')], default='P', max_length=10, verbose_name='Статья или Новость'),
        ),
    ]
